"""The `bump_ranges` task group: point jupyter-ai's dependency ranges at the
versions just released, via a PR that a human approves and the DAG merges.

This is the front of `simple_jai_release`'s Phase B. Step 0/Step 1 build the
release from the merged state of the default branch, so the bump has to land
*before* them — hence approve-then-merge inside the DAG rather than leaving a PR
for someone to merge later.

  clone_source     — clone jupyter-ai, branch off the default branch
  edit_pyproject   — rewrite the ranges (superreleaser.pyproject), build the PR body
  changes_to_push  — short-circuit: nothing changed → skip the PR/gate/merge
  open_bump_pr     — commit + push + open the PR
  approval         — human reviews the range diff
  wait_for_ci      — the PR's checks must pass before merging
  merge_bump_pr    — squash-merge so Step 0/1 see the bumped pyproject

The short-circuit exists because "no range changed" is a normal outcome, not an
error: re-running a release whose bump already merged, or releasing a wave whose
floors are already correct, both hit it — and there'd be nothing to commit.
`ignore_downstream_trigger_rules=False` keeps that skip local to this group, so
the caller's Step 0 (`trigger_rule="none_failed"`) still runs.
"""

from __future__ import annotations

from airflow.sdk import task, task_group
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.hitl import ApprovalOperator
from airflow.providers.standard.operators.python import ShortCircuitOperator

from ._common import BASE
from superreleaser import config, pyproject as pp

# The PR's branch and title, keyed on the jupyter-ai version being cut.
BRANCH = "release-bump/{version}"
TITLE = "chore: bump subpackage dependency ranges for {version}"


@task(task_id="edit_pyproject", task_display_name="Rewrite dependency ranges",
      multiple_outputs=True)
def edit_pyproject(checkout: str, wanted: dict[str, dict], version: str) -> dict:
    """Apply the wanted ranges to the checkout's pyproject.toml, in place.

    Returns `{"changes": ..., "body": ...}`: the per-package `old → new` summary
    (which is also the human gate's content) and the PR body. `changes` is empty
    when the file already says what we want — the short-circuit reads that.

    Raises if a listed subpackage isn't a jupyter-ai dependency at all: that's a
    typo or a stale registry entry, and silently bumping nothing would let the
    release ship with a stale floor.
    """
    path = f"{checkout}/pyproject.toml"
    with open(path) as f:
        text = f.read()

    missing = pp.missing_from(text, wanted)
    if missing:
        raise ValueError(
            f"not dependencies of jupyter-ai: {', '.join(missing)} — check the "
            "package names in `subpackages`"
        )

    new_text, changes = pp.apply_ranges(text, wanted)
    if changes:
        with open(path, "w") as f:
            f.write(new_text)
        for key, change in changes.items():
            print(f"{key}: {change}")
    else:
        print("no range changes needed — pyproject already matches")

    listed = "\n".join(f"- `{k}`: `{v}`" for k, v in changes.items())
    body = (
        f"Bump the dependency ranges of the subpackages released for "
        f"`jupyter-ai` {version}.\n\n{listed}\n\n"
        "*This PR was auto-generated by "
        "[superreleaser](https://github.com/dlqqq/superreleaser)*"
    )
    return {"changes": changes, "body": body}


@task(task_id="build_bump_gate", task_display_name="Build approval message")
def build_bump_gate(pr_url: str, changes: dict[str, str], version: str) -> str:
    """The Markdown shown at the bump gate — PR link + the range changes."""
    lines = [f"### Merge the dependency-range bump for `jupyter-ai` {version}?", "",
             f"**PR:** {pr_url}", "", "**Range changes:**"]
    lines += [f"- `{k}`: `{v}`" for k, v in changes.items()]
    lines += ["", "Approve to squash-merge this PR (Step 0 and Step 1 build from "
              "the merged default branch), or Reject to fail the run and merge "
              "nothing."]
    return "\n".join(lines)


@task_group(group_id="bump_ranges", group_display_name="Bump dependency ranges")
def bump_ranges(repo: str, version: str, wanted, entry_trigger_rule="all_success"):
    """Open, approve, and merge the range-bump PR.

    `wanted` maps a normalized dist name to `{"version", "range"}` (see
    `superreleaser.pyproject.apply_ranges`).

    Returns `{"entry", "exit"}` handles rather than just the last task: the group
    is entered at `clone_source`, so a caller chaining onto the returned task
    alone would leave the clone with no upstream and start it immediately.
    `entry_trigger_rule` belongs to that entry task only — set it on the group
    (never via `default_args`, which would also loosen the merge task and let it
    run after a short-circuit).
    """
    branch = BRANCH.format(version=version)
    title = TITLE.format(version=version)
    env = {"REPO": repo, "SOURCES_ROOT": str(config.SOURCES_ROOT), "BRANCH": branch}

    clone = BashOperator(
        task_id="clone_source",
        task_display_name="Clone the source repo",
        bash_command="clone_source.sh",
        env=env,
        trigger_rule=entry_trigger_rule,
        **BASE,
        output_processor=lambda o: o.strip().splitlines()[-1],  # checkout path
        doc_md="Clone the source repo locally and branch off its default branch.",
    )

    edit = edit_pyproject(clone.output, wanted, version)

    # One skip point for the whole PR→approve→merge chain. Kept local to this
    # group (ignore_downstream_trigger_rules=False) so the release itself carries
    # on when there's simply nothing to bump.
    proceed = ShortCircuitOperator(
        task_id="changes_to_push",
        task_display_name="Any range changes?",
        python_callable=bool,
        op_args=[edit["changes"]],
        ignore_downstream_trigger_rules=False,
        doc_md="Short-circuit the PR/gate/merge when no range actually changed "
        "(nothing to commit) — the release continues without a bump PR.",
    )

    open_pr = BashOperator(
        task_id="open_bump_pr",
        task_display_name="Open the bump PR",
        bash_command="open_source_pr.sh",
        env={**env, "CHECKOUT": clone.output, "TITLE": title, "BODY": edit["body"]},
        **BASE,
        output_processor=lambda o: o.strip().splitlines()[-1],  # PR URL
        doc_md="Commit the pyproject edit, push the branch, and open the PR.",
    )
    pr_url = open_pr.output

    approval = ApprovalOperator(
        task_id="approval",
        task_display_name="Await human approval",
        subject=f"dependency-range bump for jupyter-ai {version}",
        body=build_bump_gate(pr_url, edit["changes"], version),
        fail_on_reject=True,
    )

    wait_ci = BashOperator(
        task_id="wait_for_ci",
        task_display_name="Await green CI",
        bash_command='gh pr checks "$PR_URL" --watch --fail-fast --interval 30',
        env={"PR_URL": pr_url},
        **BASE,
        doc_md="Block until the PR's checks finish; pass/fail on the result.",
    )

    merge = BashOperator(
        task_id="merge_bump_pr",
        task_display_name="Merge the bump PR",
        bash_command="merge_source_pr.sh",
        env={"REPO": repo, "PR_URL": pr_url},
        **BASE,
        doc_md="Squash-merge the approved, CI-green PR so Step 0 and Step 1 build "
        "from a pyproject that names the just-released versions.",
    )

    clone >> edit >> proceed >> open_pr >> approval >> wait_ci >> merge
    return {"entry": clone, "exit": merge}
